chore: change comment formatting (#14)
* chore: change comment formatting

* fix: raraves

* fix: docker-output

* fix: pipelines

* chore: install pip

* fix: test workflow

* fix: pipeline

* fix

* fix: test suite

* remove env

* fix: docker compose

* delete vscode

* fix ?

* fix: sdf

diff --git a/.github/workflows/backend-docker-build.yml b/.github/workflows/backend-docker-build.yml
--- a/.github/workflows/backend-docker-build.yml
+++ b/.github/workflows/backend-docker-build.yml
@@ -1,4 +1,4 @@
-name: Build Docker Image
+name: Docker CI
 on:
   push:
     branches: [master, main]
@@ -13,35 +13,88 @@ jobs:
   build:
     runs-on: ubuntu-latest
     outputs:
-      docker_tag: ${{ steps.docker_tag.outputs.tag }}  
+      docker_tag: ${{ steps.docker_tag.outputs.tag }}
     steps: 
       - name: Checkout repository
         uses: actions/checkout@v3
-
+      
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
           username: ${{ vars.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
-
+      
       - name: Set Up Docker build
         uses: docker/setup-buildx-action@v2
-
+      
       - name: Determine Docker Tag
         id: docker_tag
         run: |
           if [[ "${{ github.event_name }}" == "push" ]]; then
             echo "tag=latest" >> $GITHUB_ENV
+            echo "tag=latest" >> $GITHUB_OUTPUT
           elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
             echo "tag=pr-${{ github.event.number }}" >> $GITHUB_ENV
+            echo "tag=pr-${{ github.event.number }}" >> $GITHUB_OUTPUT
           fi
-          echo "::set-output name=tag::${{ env.tag }}"  
-
-      - name: build docker image
+      
+      - name: Build docker image
         run: |
           docker build -t krystofjan/kratos-gym-be:${{ env.tag }} ./backend
-
-      - name: Push Docker imag
+      
+      - name: Push Docker image
         run: |
           docker push krystofjan/kratos-gym-be:${{ env.tag }}
 
+  # test:
+  #   needs: build
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/setup-python@v4
+  #       with:
+  #         python-version: '3.10'
+  #
+  #     - name: Login to Docker Hub
+  #       uses: docker/login-action@v3
+  #       with:
+  #         username: ${{ vars.DOCKERHUB_USERNAME }}
+  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
+  #
+  #     - name: Start Docker Compose
+  #       run: |
+  #         docker compose -f backend/docker-compose.yml up -d
+  #
+  #     - name: Wait for PostgreSQL to be ready
+  #       run: |
+  #         # Wait for PostgreSQL to be ready
+  #         docker exec postgres pg_isready -U postgres -d kratos-dev --quiet
+  #         while [ $? -ne 0 ]; do
+  #           sleep 1
+  #           docker exec postgres pg_isready -U postgres -d kratos-dev --quiet
+  #         done
+  #
+  #     - name: Run SQL Script
+  #       run: |
+  #           docker exec postgres psql -U postgres -d kratos-dev -f ./backend/db/full_db_neon.sql
+  #         
+  #
+  #     - name: Install dependencies
+  #       working-directory: ./backend/tests
+  #       run: |
+  #         python -m pip install --upgrade pip
+  #         pip install -r requirements.txt
+  #         
+  #     - name: Run tests
+  #       working-directory: ./backend/tests
+  #       env:
+  #         POSTGRES_PASSWORD: postgres
+  #         POSTGRES_USER: postgres
+  #         POSTGRES_DB: kratos-dev
+  #       run: |
+  #         pytest
+  #
+  #     - name: Cleanup
+  #       if: always()
+  #       run: |
+  #         docker compose -f backend/docker-compose.yml down
